import type { Metadata } from "next";
import { Inter, Nabla } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const Navbar = () => {
  return <div className=" h-20 flex items-center justify-between bg-slate-600 text-white ">
    <h1>Logo</h1>
    <div className=" flex justify-between ">
      <h2 className=" m-4 ">About</h2>
      <h2 className=" m-4 ">Home</h2>
      <h2 className=" m-4 " >Contacts</h2>

    </div>
  </div>
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
