import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Navbar = () => {
  return (
    <div className=" h-20 flex items-center justify-between bg-slate-600 text-white ">
      <h1>Logo</h1>
      <div className=" flex justify-between items-center ">
        <h2 className=" m-4 ">About</h2>
        <h2 className=" m-4 ">Home</h2>
        <h2 className=" m-4 ">Contacts</h2>
        <Button className=" m-4  " variant={"destructive"}> Sign in </Button>
      </div>
    </div>
  );
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
